Esercitazione_Polizia/Controllers/HomeController.cs
using Esercitazione_Polizia.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Esercitazione_Polizia.Controllers
{
    public class HomeController : Controller
    {
        private readonly string connectionString = ConfigurationManager.ConnectionStrings["PoliziaDB"].ConnectionString;

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Esercitazione_Polizia/Controllers/VerbaleController.cs
using Esercitazione_Polizia.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Esercitazione_Polizia.Controllers
{
    public class VerbaleController : Controller
    {
        private readonly string connectionString = ConfigurationManager.ConnectionStrings["PoliziaDB"].ConnectionString;

        // GET: Verbale
        public ActionResult Index()
        {

            SqlConnection conn = new SqlConnection(connectionString);
            List<Verbale> listaVerbali = new List<Verbale>();

            try
            {
                conn.Open();

                string query = "SELECT * FROM Verbali";
                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Verbale verbale = new Verbale
                    {
                        IDVerbale = Convert.ToInt32(reader["IDVerbale"]),
                        IDTrasgressore = Convert.ToInt32(reader["IDTrasgressore"]),
                        IDViolazione = Convert.ToInt32(reader["IDViolazione"]),
                        DataViolazione = Convert.ToDateTime(reader["DataViolazione"]),
                        Nominativo_Agente = reader["Nominativo_Agente"].ToString(),

                    };

                    listaVerbali.Add(verbale);
                }
            }
            catch (Exception ex)
            {
                Response.Write($"Si è verificato un errore: {ex.Message}");
            }
            finally
            {
                conn.Close();
            }

            return View(listaVerbali);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Verbale nuovoVerbale)
        {
            SqlConnection conn = new SqlConnection(connectionString);

            try
            {
                conn.Open();

                string query = "INSERT INTO Verbali (IDTrasgressore, IDViolazione, DataViolazione, Nominativo_Agente) " +
                               "VALUES (@IDTrasgressore, @IDViolazione, @Data_Violazione, @Nominativo_Agente)";

                SqlCommand cmd = new SqlCommand(query, conn);
                cmd.Parameters.AddWithValue("@IDTrasgressore", nuovoVerbale.IDTrasgressore);
                cmd.Parameters.AddWithValue("@IDViolazione", nuovoVerbale.IDViolazione);
                cmd.Parameters.AddWithValue("@Data_Violazione", nuovoVerbale.DataViolazione);
                cmd.Parameters.AddWithValue("@Nominativo_Agente", nuovoVerbale.Nominativo_Agente);

                cmd.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                Response.Write($"Si è verificato un errore: {ex.Message}");
            }
            finally
            {
                conn.Close();
            }

            return View();
        }

        
    }
}

Esercitazione_Polizia/Controllers/ViolazioneController.cs
using Esercitazione_Polizia.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Esercitazione_Polizia.Controllers
{

    public class ViolazioneController : Controller
    {
        private readonly string connectionString = ConfigurationManager.ConnectionStrings["PoliziaDB"].ConnectionString;

        // GET: Violazione
        public ActionResult Index()
        {
            SqlConnection conn = new SqlConnection(connectionString);
            List<Violazione> listaViolazioni = new List<Violazione>();

            try
            {
                conn.Open();

                string query = "SELECT * FROM Violazioni WHERE Contestabile = 'true'";
                SqlCommand cmd = new SqlCommand(query, conn);
                SqlDataReader reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    Violazione violazione = new Violazione(
                        Convert.ToInt32(reader["IDViolazione"]),
                        reader["Descrizione"].ToString(),
                        Convert.ToInt32(reader["PuntiDecurtati"]),
                        Convert.ToDecimal(reader["Importo"]),
                        Convert.ToBoolean(reader["Contestabile"].ToString())
                        );

                    listaViolazioni.Add(violazione);
                }
            }
            catch (Exception ex)
            {

                Response.Write($"Si è verificato un errore: {ex.Message}");
            }
            finally
            {
                conn.Close();
            }

            return View(listaViolazioni);
        }
        
    }
}

Esercitazione_Polizia/Views/Home/Index.cshtml
@model IEnumerable<Esercitazione_Polizia.Models.Violazione>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="jumbotron">
        <h1 class="display-4 mb-3">Benvenuto nell'Archivio della Polizia Municipale</h1>
        <p class="lead mb-5">
            Esplora le funzionalità del nostro sistema per gestire in modo efficiente le informazioni relative ai trasgressori e ai verbali emessi dalla Polizia Municipale. Visualizza l'elenco completo dei trasgressori, compila nuovi verbali e monitora le violazioni in dettaglio.
        </p>
    </div>
</div>

<div class="row row-cols-3">
    <div class="col">
        <div class="card text-center">
            <div class="card-body">
                <h2 class="card-title">Trasgressori</h2>
                <p class="card-text">Visualizza e gestisci i trasgressori.</p>
                @Html.ActionLink("Visualizza Trasgressori", "Index", "Trasgressore", null, new { @class = "btn btn-dark btn-rounded" })
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-center">
            <div class="card-body">
                <h2 class="card-title">Verbali</h2>
                <p class="card-text">Compila i verbali delle violazioni.</p>
                @Html.ActionLink("Compila Verbale", "Create", "Verbale",null, new { @class = "btn btn-dark btn-rounded" })
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-center">
            <div class="card-body">
                <h2 class="card-title">Violazioni</h2>
                <p class="card-text">Visualizza informazioni dettagliate sulle violazioni.</p>
                @Html.ActionLink("Visualizza Elenco Violazioni", "Index", "Violazione",null, new { @class = "btn btn-dark btn-rounded" })
            </div>
        </div>
    </div>
</div>